### ISSUE TITLE
Share checklist

### ISSUE THREAD

**Issue by DarthMikke** [DarthMikke/remember_react#23]
- [x] Checklist details to the right of the title
- [x] Action: Share with…
  - [x] Search API
  - [x] Share API
- [x] Unshare checklist
  - [x] Dropdown menu with list of users
  - [x] Unshare button
  - [x] Unshare API
- [x] Only owner can share or delete checklist.
